### ISSUE TITLE
None of the sites work with securely 

### ISSUE THREAD

**Issue by Marjamjelly** [IamChristianS/v1#34]
I would like to use this site, but it does not work with securely. What should I do?

**Comment by unbl0ck** [comment]
Sadly, there is nothing that can be done on my end (apart from creating new sites). However, the best way to avoid this is to simply fork the repo, and host it completely for free with GitHub Pages. If you have any questions, ask away.

**Comment by Marjamjelly** [comment]
I forked it and ran it on GitHub pages, but I can only see the “popular” games. Are there others?

**Comment by unbl0ck** [comment]
Yes, there should be a navigation bar at the top. In this build of the site, there are some times where it will not load (still havent found the cause), but after a reload or two, it should appear.
