### ISSUE TITLE
game

### ISSUE THREAD

**Issue by ineedperqs** [IamChristianS/v1#35]
when I try to play a game it keeps saying this file can't be accessed idk what to do to fix it.

**Comment by IamChristianS** [comment]
Okay, I'll need some info before I can help troubleshoot. Can you give me the site URL, what game you are trying to access, and what browser you use?

**Comment by IamChristianS** [comment]
I'm gonna close this issue due to inactivity and the issue most likely being caused by another hoster. If you are still experiencing this, feel free to email me and I will help you however I can.
